services: 
  web:
    image: marcosgrc/webapp04:latest
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/bytemarket
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DLL_AUTO=create-drop
    restart: on-failure
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bytemarket
  frontend:
    build:
      context: ../frontend
      dockerfile: webapp04/Docker/Dockerfile 
    ports:
      - 4200:80
    container_name: bytemarket-frontend
